### ISSUE TITLE
Neurosky mindwave to touchdesigner 

### ISSUE THREAD

**Issue by 4130Z** [JesseScott/disconnect#1]
Hey Scott

Thank u to share your project , I already download your toe file but I can't run it  successfully ，

system says:
"warning: skipping unrecognized parameter "r" value : 180 (perform/project1/transform1.parm)"

So i cant figure out what problem is , I'm using the Mindwave mobile 2 

Thanks!!

**Comment by JesseScott** [comment]
Do you have a custom name on your .toe ?

**Comment by 4130Z** [comment]
No,  I didn't renamed .toe file when I run it , I already try all your .toe ,and the warning is all same. and i tried to renamed .toe , but nothing change , still have warning.

head phone is successfully connected  , but the data seems like not transmit to touchdesigner. 

I want to trans the EEG to my custom 3d model . 

So I think u work can help me alot ,thanks!

**Comment by 4130J** [comment]
> 嘿斯科特
> 
> 感谢您分享您的项目，我已经下载了您的脚趾文件，但我无法成功运行它，
> 
> 系统说：
> “警告：跳过无法识别的参数”r“值：180（执行/ project1 / transform1.parm）”
> 
> 所以我无法弄清楚问题是什么，我正在使用Mindwave手机2
> 
> 谢谢！！

**Comment by 4130Z** [comment]
BTW: The warning is from touchdesigner not my PC

**Comment by JesseScott** [comment]
Yeah i understand that. Is this an error or a warning?

**Comment by 4130Z** [comment]
Load Project .toe: disconnect.8.toe load warnings:
warning: skipping unrecognized parameter "r" value : 180 (perform/project1/transform1.parm)


> Yeah i understand that. Is this an error or a warning?

**Comment by 4130Z** [comment]
Hey Scott
Now I just  solved error and warning,   
I think is caused by TD versions, I noticed that you version is 077 my version is 088.

I maintain your DAT and CHOP structure and I saved it in my 088, 
I sure the headphones is working  and successful link to TD, and I checked JSON file is outputting data.
<img width="1065" alt="2019-03-01 22 44 51" src="https://user-images.githubusercontent.com/32266288/53645493-f3298180-3c73-11e9-9a05-09749e686ac3.png">
<img width="828" alt="2019-03-01 22 47 47" src="https://user-images.githubusercontent.com/32266288/53645550-0f2d2300-3c74-11e9-915f-843b69e1f25a.png">

but I the value in DAT is still not changing, like it's not updated.
<img width="994" alt="2019-03-01 22 49 49" src="https://user-images.githubusercontent.com/32266288/53645927-f5401000-3c74-11e9-82fe-52d893ea907c.png">
<img width="935" alt="2019-03-01 22 50 07" src="https://user-images.githubusercontent.com/32266288/53645939-fe30e180-3c74-11e9-84ad-9b9760dfa1c9.png">

Now i don‘t know which problem caused this situation.

Im a beginner of TD,  I will be grateful if you can release more information of your work about TD setting or system environment setting  !!
I am using mac OS 10.14 
Thanks!!

**Comment by JesseScott** [comment]
Okay. It's been a while since I've looked at this, and don't even have TD installed anymore, but will try to take a look next week.

**Comment by JesseScott** [comment]
My name is Jesse btw :)

**Comment by 4130Z** [comment]
> 我的名字是杰西顺便说一句:)

Thanks for ur attention ！Jesse！

**Comment by shuming9886** [comment]
> Hey Scott Now I just solved error and warning, I think is caused by TD versions, I noticed that you version is 077 my version is 088.
> 
> I maintain your DAT and CHOP structure and I saved it in my 088, I sure the headphones is working and successful link to TD, and I checked JSON file is outputting data. <img alt="2019-03-01 22 44 51" width="1065" src="https://user-images.githubusercontent.com/32266288/53645493-f3298180-3c73-11e9-9a05-09749e686ac3.png"> <img alt="2019-03-01 22 47 47" width="828" src="https://user-images.githubusercontent.com/32266288/53645550-0f2d2300-3c74-11e9-915f-843b69e1f25a.png">
> 
> but I the value in DAT is still not changing, like it's not updated. <img alt="2019-03-01 22 49 49" width="994" src="https://user-images.githubusercontent.com/32266288/53645927-f5401000-3c74-11e9-82fe-52d893ea907c.png"> <img alt="2019-03-01 22 50 07" width="935" src="https://user-images.githubusercontent.com/32266288/53645939-fe30e180-3c74-11e9-84ad-9b9760dfa1c9.png">
> 
> Now i don‘t know which problem caused this situation.
> 
> Im a beginner of TD, I will be grateful if you can release more information of your work about TD setting or system environment setting !! I am using mac OS 10.14 Thanks!!

Hi, Thank u to share your problem , I already download @JesseScott 's toe file but I can't run it successfully. I can only connect through ports in TD, **not through TCP/IP.** I don't know where the problem is. I look forward to your answer. Thank you！I use the Neurosky Mindwave mobile 2!

**Comment by shuming9886** [comment]
> 

Hi，May I ask you a question? I want to know how there is a 'debug output' window, I can't find the values for attention and mediation. Is it in disconnect.8.toe?

**Comment by shuming9886** [comment]
> Hey Scott Now I just solved error and warning, I think is caused by TD versions, I noticed that you version is 077 my version is 088.
> 
> I maintain your DAT and CHOP structure and I saved it in my 088, I sure the headphones is working and successful link to TD, and I checked JSON file is outputting data. <img alt="2019-03-01 22 44 51" width="1065" src="https://user-images.githubusercontent.com/32266288/53645493-f3298180-3c73-11e9-9a05-09749e686ac3.png"> <img alt="2019-03-01 22 47 47" width="828" src="https://user-images.githubusercontent.com/32266288/53645550-0f2d2300-3c74-11e9-915f-843b69e1f25a.png">
> 
> but I the value in DAT is still not changing, like it's not updated. <img alt="2019-03-01 22 49 49" width="994" src="https://user-images.githubusercontent.com/32266288/53645927-f5401000-3c74-11e9-82fe-52d893ea907c.png"> <img alt="2019-03-01 22 50 07" width="935" src="https://user-images.githubusercontent.com/32266288/53645939-fe30e180-3c74-11e9-84ad-9b9760dfa1c9.png">
> 
> Now i don‘t know which problem caused this situation.
> 
> Im a beginner of TD, I will be grateful if you can release more information of your work about TD setting or system environment setting !! I am using mac OS 10.14 Thanks!!

Hi，May I ask you a question? I want to know how there is a 'debug output' window, I can't find the values for attention and mediation. Is it in disconnect.8.toe?

**Comment by JesseScott** [comment]
Not sure if I recall where I put it TBH!

Feel free to open a PR if you think of a better place, or want to commit w/ the version support for 088+

**Comment by JesseScott** [comment]
Closing as resolved
