### ISSUE TITLE
Can not connet through TCP/IP

### ISSUE THREAD

**Issue by shuming9886** [JesseScott/disconnect#2]
Hi, Thank u to share your projects , I already download toe file but I can't run it successfully. 

**I can only connect through ports in TD, not through TCP/IP.** 

I don't know where the problem is. 

I look forward to your answer. Thank you！I use the Neurosky Mindwave mobile 2!
<img width="434" alt="截屏2023-07-03 21 26 24" src="https://github.com/JesseScott/disconnect/assets/26901799/abb4d2ba-9ea0-4815-a887-313a2448047c">
<img width="436" alt="截屏2023-07-03 21 26 12" src="https://github.com/JesseScott/disconnect/assets/26901799/ff98774b-04ee-4817-ae65-43db0f3b492c">

**Comment by JesseScott** [comment]
@shuming9886 looks like you figured this out?
